name: AsymmetricCritic_lstm
minibatch_size: 16384 
mini_epochs: 4
learning_rate: 5e-5
normalize_input: True
truncate_grads: True

network:
  asymmetric_critic: True
  separate_value_mlp: False

  mlp:
    units: [1024, 512] 
  rnn:
    name: lstm
    units: 2048 
    layers: 1
    before_mlp: False
    layer_norm: True
    concat_input: False
    concat_output: True
